{"uuid": "ea8ef235-b262-424a-b48f-46beb89cf30b", "children": ["0c7a7e15-7eb6-411e-99ea-7aff4351b3fa", "a1315384-237e-43bf-b981-763e8395a891", "d44025f4-c602-4ca1-8648-713493c1028d", "cac4c3d3-c952-4efa-b9ef-feedbaf5b280"], "befores": [{"name": "xunit_setup_class_fixture_TestMine", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"/Users/jike/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/jike/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/jike/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/jike/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"/Users/jike/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/_pytest/python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"/Users/jike/PycharmProjects/pythonProject/tests/test_01_mine.py\", line 11, in setup_class\n    init().check_login_status()\n"}, "start": 1656059236351, "stop": 1656059236351}], "start": 1656059236351, "stop": 1656059236431}